# Generated by Django 4.0.6 on 2023-11-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.vendor'),
        ),
    ]
